# Generated by Django 3.0.5 on 2021-01-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
