# Generated by Django 3.0.5 on 2021-01-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_delete_entry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
