# Generated by Django 3.0.5 on 2021-01-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20210120_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='military1_service_status',
            new_name='military_service_status',
        ),
    ]
